apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: nexus-pvc
  namespace: nexus
  labels: 
    app: nexus
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 
