apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    nginx.org/client-max-body-size: 200m
  name: docker-ingress
  namespace: tools
spec:
  rules:
  - host: docker.fuchicorp.com
    http:
      paths:
      - backend:
          serviceName: nexus-service
          servicePort: 8085
