apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: fscoding
  labels:
    run: fscoding
  name: fscoding
spec:
  replicas: 4
  selector:
    matchLabels:
      run: fscoding
  template:
    metadata:
      labels:
        run: fscoding
    spec:
      containers:
      - image: 192.168.3.56:8085/fscoding:latest
        name: fscoding
        ports:
        - containerPort: 8888
        command: ["python3.6"]
        args: ["/root/app.py"]
      imagePullSecrets:
      - name: registrypullsecret
