apiVersion: v1
kind: Pod
metadata:
  labels:
    run: private-reg
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: 192.168.3.56:8085/fscoding:latest
    command: ["python3.6"]
    args: ["/root/app.py"]
  imagePullSecrets:
  - name: registrypullsecret
