apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fuchicorp-api
rules:
  -
    apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
    resources:
      - configmaps
      - daemonsets
      - deployments
      - ingress
      - limitranges
      - namespaces
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - serviceaccounts
      - services
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fuchicorp-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fuchicorp-api
subjects:
- kind: ServiceAccount
  name: fuchicorp-api
  namespace: default
