apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
  namespace: tools
  labels:
    app: vault-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: vault-deployment
  name: vault
  namespace: tools
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-deployment
    spec:
      containers:
      - image: vault
        name: vault
        ports:
        - containerPort: 8200
          protocol: TCP
        securityContext:
         capabilities:
           add:
             - IPC_LOCK
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          valueFrom:
            secretKeyRef:
              name: vault-secret
              key: password
        volumeMounts:
          - mountPath: /var/run
            name: vault-pvc
      volumes:
        - name: vault-pvc
          persistentVolumeClaim:
            claimName: vault-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: vault-service
  labels:
    app: vault-deployment
  namespace: tools
spec:
  ports:
    - name: vault
      port: 80
      targetPort: 8200
  selector:
    app: vault-deployment
  type: LoadBalancer
