apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: tools
  labels:
    app: grafana
    component: core
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - port: 80
      targetPort: 8083
    - port: 8083
      targetPort: 8081
      protocol: TCP