apiVersion: v1
kind: Service
metadata:
  labels:
    app: jira
  name: jira
  namespace: tools
spec:
  ports:
    - nodePort: 30555
      port: 80
      targetPort: 8084
  selector:
    app: jira
  type: NodePort
