apiVersion: v1
kind: Service
metadata:
  labels:
    app: jira
  name: jira
  namespace: tools
spec:
  ports:
    - nodePort: 30555
      port: 8084
      targetPort: 8080
  selector:
    app: jira
  type: NodePort
