apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-pod
    name: jenkins-pod
  name: jenkins-pod-645f85d8b6-4grcj
  namespace: TOOLS
spec:
  ports:
  - nodePort: 30619
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins-pod
    name: jenkins-pod
  type: LoadBalancer
